pidfile = 'o24-prod.pid'
worker_tmp_dir = '/dev/shm'
worker_class = 'gthread'
workers = 6
worker_connections = 1000
timeout = 30
keepalive = 2
threads = 6
proc_name = 'o24-prod'
bind = 'unix:/home/o24user/o24-prod.sock'
backlog = 2048
accesslog = '/home/o24user/logs/prod/gunicorn_access_log'
acceslogformat ="%(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s %(f)s %(a)s"
errorlog =  '/home/o24user/logs/prod/gunicorn_error_log'
user = 'o24user'
group = 'o24user'
